name:                omni-02regex
version:             0.1.0.0
github:              "panaeon/omni-02regex"
license:             BSD3
author:              "vitalii voloshyn"
maintainer:          "example@example.com"
copyright:           "2018 vitalii voloshyn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/panaeon/omni-02regex#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- random
- containers
- unordered-containers
- monad-loops
- pqueue
- vector
- lens
- strict
- array
- comonad
- bytestring
- contravariant
- megaparsec >= 6.4.1


library:
  source-dirs: src


executables:
  omni-02regex-exe:
    main:                Main.hs
    source-dirs:         app

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - omni-02regex

tests:
  omni-02regex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - omni-02regex
    - hspec
    - QuickCheck
